### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by ChaseC99** [icssc-projects/Zotistics#2]
Update the website metadata for Zotistics. 

Currently the description is "Web site created using create-react-app" and the link preview looks like this:
![image](https://user-images.githubusercontent.com/29494270/140624371-0c2de9e6-e938-465f-a99d-a3ef342e052e.png)

Link in the code:
https://github.com/icssc-projects/Zotistics/blob/16517fded78cf840581d425d1200275af66a29f6/public/index.html#L10

**Comment by patrickanguyen** [comment]
Forgot to mention, but this issue was resolved in PR #25
