### ISSUE TITLE
Application crashes when no classes are found

### ISSUE THREAD

**Issue by patrickanguyen** [icssc-projects/Zotistics#23]
# Description
When you select options with no classes found, the application turns to white. The reason for this crash is [Line 10 of Data.js](https://github.com/icssc-projects/Zotistics/blob/701cc0b772be19d8720791a9ea1b0d3c686e1e14/src/Components/Data/Data.js#L10), where the anonymous function raises an exception when the array is empty. 

# Steps to reproduce
1. Select `Alfaro, S.` as the instructor, and `Bio Sci` as the Department.
2. When the `Submit` button is pressed, a crash will occur.

**Comment by alexanderl19** [comment]
We're planning to remove the client side grade manipulation in favor of solely using the api for grade sums.
