### ISSUE TITLE
Instructor field autocomplete changes suddenly upon selection

### ISSUE THREAD

**Issue by patrickanguyen** [icssc-projects/Zotistics#28]
# Summary
The instructor autocompletes changes suddenly upon selection. It changes from the default instructors to instructors starting in alphabetical order

# Video
https://user-images.githubusercontent.com/41417417/148733233-c7adf0d1-565e-4df7-8664-47f790d0626d.mp4

**Comment by alexanderl19** [comment]
This issue should be addressed with the new input library. #29
